// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAONwRrD4wUPNc5g96uFPIEJXSGREQxbbY',
    appId: '1:1037769887678:web:472d7b71cdbeb1866333ef',
    messagingSenderId: '1037769887678',
    projectId: 'class-92d9e',
    authDomain: 'class-92d9e.firebaseapp.com',
    storageBucket: 'class-92d9e.firebasestorage.app',
    measurementId: 'G-W8S4Y6WDTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cS-oFDepRwLQMmZM50V05dtE9M2P7e4',
    appId: '1:1037769887678:android:a6c8c3fe001f58406333ef',
    messagingSenderId: '1037769887678',
    projectId: 'class-92d9e',
    storageBucket: 'class-92d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sjUy4EVHAn1mXYJOgiY1s-JfARgMOIw',
    appId: '1:1037769887678:ios:bc393e3ec43026e46333ef',
    messagingSenderId: '1037769887678',
    projectId: 'class-92d9e',
    storageBucket: 'class-92d9e.firebasestorage.app',
    iosBundleId: 'com.example.classroom37',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sjUy4EVHAn1mXYJOgiY1s-JfARgMOIw',
    appId: '1:1037769887678:ios:bc393e3ec43026e46333ef',
    messagingSenderId: '1037769887678',
    projectId: 'class-92d9e',
    storageBucket: 'class-92d9e.firebasestorage.app',
    iosBundleId: 'com.example.classroom37',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAONwRrD4wUPNc5g96uFPIEJXSGREQxbbY',
    appId: '1:1037769887678:web:b458128bef94f3fb6333ef',
    messagingSenderId: '1037769887678',
    projectId: 'class-92d9e',
    authDomain: 'class-92d9e.firebaseapp.com',
    storageBucket: 'class-92d9e.firebasestorage.app',
    measurementId: 'G-CEZCM85TLG',
  );

}